include themes/noctalia.conf
shell /bin/zsh
allow_remote_control yes

font_family      Adwaita Mono
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 10.0


# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
